version: '3.8'
services:
  browser-protection:
    build: 
      context: .
      shm_size: '2gb'
    volumes:
      - ./components:/app/components:ro
      - ./patches:/app/patches:ro
    environment:
      - PROTECTION_LEVEL=HIGH
      - ENABLE_NEURAL_EVASION=true
      - ENABLE_QUANTUM_RESISTANT=true
      - PYTHONPATH=/app
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
