name: Codespaces Sync

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-codespaces:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: GitHub Codespaces Pre-build
        uses: github/codespaces-pre-build@v1
        with:
          prebuild-command: |
          
            # Add any additional setup commands needed
            python3 -m protection_system.initialize \
              --chrome-path=/usr/local/bin/ungoogled-chromium \
              --protection-level=maximum \
              --enable-all-features
